AWSTemplateFormatVersion: "2010-09-09"
Description:
  Creates an S3 bucket configured for hosting a static website, and a Route
  53 DNS record pointing to the bucket
Parameters:
  FullDomainName:
    Type: String
    Description: The full domain name e.g. www.jevsejev.io
    Default: homecook-object-pool
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref "FullDomainName"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    DeletionPolicy: Retain
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref "WebsiteBucket"
      PolicyDocument:
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Join ["", ["arn:aws:s3:::", !Ref "WebsiteBucket", /*]]
Outputs:
  BucketName:
    Value: !Ref "WebsiteBucket"
    Description: Name of S3 bucket to hold website content
